### ISSUE TITLE
Create repositories for rpi images

### ISSUE THREAD

**Issue by venkatnsrinivasan** [kairos-io/provider-rke2#22]
We need following docker image repositories for building the rpi based images

core-opensuse-arm-rpi-rke2
core-ubuntu-20-lts-arm-rpi-rke2
core-ubuntu-22-lts-arm-rpi-rke2
core-alpine-arm-rpi-rke2

**Comment by mauromorales** [comment]
Added them in quay:

- https://quay.io/repository/kairos/core-opensuse-arm-rpi-rke2
- https://quay.io/repository/kairos/core-ubuntu-20-lts-arm-rpi-rke2
- https://quay.io/repository/kairos/core-ubuntu-22-lts-arm-rpi-rke2
- https://quay.io/repository/kairos/core-alpine-arm-rpi-rke2

Have a look and let me know if it's all good

**Comment by jimmykarily** [comment]
Closing as done. @venkatnsrinivasan please open again if something is not right.
